//
//  Countries.swift
//  Whooliday
//
//  Created by Tommaso Diegoli on 25/06/24.
//

class Country: Identifiable, Codable, Hashable, CustomStringConvertible {
    let name: String
    let alpha2Code: String
    
    init(name: String, alpha2Code: String) {
        self.name = name
        self.alpha2Code = alpha2Code
    }
    
    // Implementing Hashable
    func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(alpha2Code)
    }
    
    static func == (lhs: Country, rhs: Country) -> Bool {
        return lhs.name == rhs.name && lhs.alpha2Code == rhs.alpha2Code
    }
    
    // Implementing CustomStringConvertible
    var description: String {
        return name
    }
    
    
    static var allCountries: [Country] {
        [
            Country(name: "Afghanistan", alpha2Code: "af"),
            Country(name: "Albania", alpha2Code: "al"),
            Country(name: "Algeria", alpha2Code: "dz"),
            Country(name: "Andorra", alpha2Code: "ad"),
            Country(name: "Angola", alpha2Code: "ao"),
            Country(name: "Antigua and Barbuda", alpha2Code: "ag"),
            Country(name: "Argentina", alpha2Code: "ar"),
            Country(name: "Armenia", alpha2Code: "am"),
            Country(name: "Australia", alpha2Code: "au"),
            Country(name: "Austria", alpha2Code: "at"),
            Country(name: "Azerbaijan", alpha2Code: "az"),
            Country(name: "Bahamas", alpha2Code: "bs"),
            Country(name: "Bahrain", alpha2Code: "bh"),
            Country(name: "Bangladesh", alpha2Code: "bd"),
            Country(name: "Barbados", alpha2Code: "bb"),
            Country(name: "Belarus", alpha2Code: "by"),
            Country(name: "Belgium", alpha2Code: "be"),
            Country(name: "Belize", alpha2Code: "bz"),
            Country(name: "Benin", alpha2Code: "bj"),
            Country(name: "Bhutan", alpha2Code: "bt"),
            Country(name: "Bolivia (Plurinational State of)", alpha2Code: "bo"),
            Country(name: "Bosnia and Herzegovina", alpha2Code: "ba"),
            Country(name: "Botswana", alpha2Code: "bw"),
            Country(name: "Brazil", alpha2Code: "br"),
            Country(name: "Brunei Darussalam", alpha2Code: "bn"),
            Country(name: "Bulgaria", alpha2Code: "bg"),
            Country(name: "Burkina Faso", alpha2Code: "bf"),
            Country(name: "Burundi", alpha2Code: "bi"),
            Country(name: "Cabo Verde", alpha2Code: "cv"),
            Country(name: "Cambodia", alpha2Code: "kh"),
            Country(name: "Cameroon", alpha2Code: "cm"),
            Country(name: "Canada", alpha2Code: "ca"),
            Country(name: "Central African Republic", alpha2Code: "cf"),
            Country(name: "Chad", alpha2Code: "td"),
            Country(name: "Chile", alpha2Code: "cl"),
            Country(name: "China", alpha2Code: "cn"),
            Country(name: "Colombia", alpha2Code: "co"),
            Country(name: "Comoros", alpha2Code: "km"),
            Country(name: "Congo", alpha2Code: "cg"),
            Country(name: "Costa Rica", alpha2Code: "cr"),
            Country(name: "Côte d'Ivoire", alpha2Code: "ci"),
            Country(name: "Croatia", alpha2Code: "hr"),
            Country(name: "Cuba", alpha2Code: "cu"),
            Country(name: "Cyprus", alpha2Code: "cy"),
            Country(name: "Czechia", alpha2Code: "cz"),
            Country(name: "Democratic People's Republic of Korea", alpha2Code: "kp"),
            Country(name: "Democratic Republic of the Congo", alpha2Code: "cd"),
            Country(name: "Denmark", alpha2Code: "dk"),
            Country(name: "Djibouti", alpha2Code: "dj"),
            Country(name: "Dominica", alpha2Code: "dm"),
            Country(name: "Dominican Republic", alpha2Code: "do"),
            Country(name: "Ecuador", alpha2Code: "ec"),
            Country(name: "Egypt", alpha2Code: "eg"),
            Country(name: "El Salvador", alpha2Code: "sv"),
            Country(name: "Equatorial Guinea", alpha2Code: "gq"),
            Country(name: "Eritrea", alpha2Code: "er"),
            Country(name: "Estonia", alpha2Code: "ee"),
            Country(name: "Eswatini", alpha2Code: "sz"),
            Country(name: "Ethiopia", alpha2Code: "et"),
            Country(name: "Fiji", alpha2Code: "fj"),
            Country(name: "Finland", alpha2Code: "fi"),
            Country(name: "France", alpha2Code: "fr"),
            Country(name: "Gabon", alpha2Code: "ga"),
            Country(name: "Gambia", alpha2Code: "gm"),
            Country(name: "Georgia", alpha2Code: "ge"),
            Country(name: "Germany", alpha2Code: "de"),
            Country(name: "Ghana", alpha2Code: "gh"),
            Country(name: "Greece", alpha2Code: "gr"),
            Country(name: "Grenada", alpha2Code: "gd"),
            Country(name: "Guatemala", alpha2Code: "gt"),
            Country(name: "Guinea", alpha2Code: "gn"),
            Country(name: "Guinea-Bissau", alpha2Code: "gw"),
            Country(name: "Guyana", alpha2Code: "gy"),
            Country(name: "Haiti", alpha2Code: "ht"),
            Country(name: "Honduras", alpha2Code: "hn"),
            Country(name: "Hungary", alpha2Code: "hu"),
            Country(name: "Iceland", alpha2Code: "is"),
            Country(name: "India", alpha2Code: "in"),
            Country(name: "Indonesia", alpha2Code: "id"),
            Country(name: "Iran (Islamic Republic of)", alpha2Code: "ir"),
            Country(name: "Iraq", alpha2Code: "iq"),
            Country(name: "Ireland", alpha2Code: "ie"),
            Country(name: "Israel", alpha2Code: "il"),
            Country(name: "Italy", alpha2Code: "it"),
            Country(name: "Jamaica", alpha2Code: "jm"),
            Country(name: "Japan", alpha2Code: "jp"),
            Country(name: "Jordan", alpha2Code: "jo"),
            Country(name: "Kazakhstan", alpha2Code: "kz"),
            Country(name: "Kenya", alpha2Code: "ke"),
            Country(name: "Kiribati", alpha2Code: "ki"),
            Country(name: "Kuwait", alpha2Code: "kw"),
            Country(name: "Kyrgyzstan", alpha2Code: "kg"),
            Country(name: "Lao People's Democratic Republic", alpha2Code: "la"),
            Country(name: "Latvia", alpha2Code: "lv"),
            Country(name: "Lebanon", alpha2Code: "lb"),
            Country(name: "Lesotho", alpha2Code: "ls"),
            Country(name: "Liberia", alpha2Code: "lr"),
            Country(name: "Libya", alpha2Code: "ly"),
            Country(name: "Liechtenstein", alpha2Code: "li"),
            Country(name: "Lithuania", alpha2Code: "lt"),
            Country(name: "Luxembourg", alpha2Code: "lu"),
            Country(name: "Madagascar", alpha2Code: "mg"),
            Country(name: "Malawi", alpha2Code: "mw"),
            Country(name: "Malaysia", alpha2Code: "my"),
            Country(name: "Maldives", alpha2Code: "mv"),
            Country(name: "Mali", alpha2Code: "ml"),
            Country(name: "Malta", alpha2Code: "mt"),
            Country(name: "Marshall Islands", alpha2Code: "mh"),
            Country(name: "Mauritania", alpha2Code: "mr"),
            Country(name: "Mauritius", alpha2Code: "mu"),
            Country(name: "Mexico", alpha2Code: "mx"),
            Country(name: "Micronesia (Federated States of)", alpha2Code: "fm"),
            Country(name: "Monaco", alpha2Code: "mc"),
            Country(name: "Mongolia", alpha2Code: "mn"),
            Country(name: "Montenegro", alpha2Code: "me"),
            Country(name: "Morocco", alpha2Code: "ma"),
            Country(name: "Mozambique", alpha2Code: "mz"),
            Country(name: "Myanmar", alpha2Code: "mm"),
            Country(name: "Namibia", alpha2Code: "na"),
            Country(name: "Nauru", alpha2Code: "nr"),
            Country(name: "Nepal", alpha2Code: "np"),
            Country(name: "Netherlands", alpha2Code: "nl"),
            Country(name: "New Zealand", alpha2Code: "nz"),
            Country(name: "Nicaragua", alpha2Code: "ni"),
            Country(name: "Niger", alpha2Code: "ne"),
            Country(name: "Nigeria", alpha2Code: "ng"),
            Country(name: "North Macedonia", alpha2Code: "mk"),
            Country(name: "Norway", alpha2Code: "no"),
            Country(name: "Oman", alpha2Code: "om"),
            Country(name: "Pakistan", alpha2Code: "pk"),
            Country(name: "Palau", alpha2Code: "pw"),
            Country(name: "Panama", alpha2Code: "pa"),
            Country(name: "Papua New Guinea", alpha2Code: "pg"),
            Country(name: "Paraguay", alpha2Code: "py"),
            Country(name: "Peru", alpha2Code: "pe"),
            Country(name: "Philippines", alpha2Code: "ph"),
            Country(name: "Poland", alpha2Code: "pl"),
            Country(name: "Portugal", alpha2Code: "pt"),
            Country(name: "Qatar", alpha2Code: "qa"),
            Country(name: "Republic of Korea", alpha2Code: "kr"),
            Country(name: "Republic of Moldova", alpha2Code: "md"),
            Country(name: "Romania", alpha2Code: "ro"),
            Country(name: "Russian Federation", alpha2Code: "ru"),
            Country(name: "Rwanda", alpha2Code: "rw"),
            Country(name: "Saint Kitts and Nevis", alpha2Code: "kn"),
            Country(name: "Saint Lucia", alpha2Code: "lc"),
            Country(name: "Saint Vincent and the Grenadines", alpha2Code: "vc"),
            Country(name: "Samoa", alpha2Code: "ws"),
            Country(name: "San Marino", alpha2Code: "sm"),
            Country(name: "Sao Tome and Principe", alpha2Code: "st"),
            Country(name: "Saudi Arabia", alpha2Code: "sa"),
            Country(name: "Senegal", alpha2Code: "sn"),
            Country(name: "Serbia", alpha2Code: "rs"),
            Country(name: "Seychelles", alpha2Code: "sc"),
            Country(name: "Sierra Leone", alpha2Code: "sl"),
            Country(name: "Singapore", alpha2Code: "sg"),
            Country(name: "Slovakia", alpha2Code: "sk"),
            Country(name: "Slovenia", alpha2Code: "si"),
            Country(name: "Solomon Islands", alpha2Code: "sb"),
            Country(name: "Somalia", alpha2Code: "so"),
            Country(name: "South Africa", alpha2Code: "za"),
            Country(name: "South Sudan", alpha2Code: "ss"),
            Country(name: "Spain", alpha2Code: "es"),
            Country(name: "Sri Lanka", alpha2Code: "lk"),
            Country(name: "Sudan", alpha2Code: "sd"),
            Country(name: "Suriname", alpha2Code: "sr"),
            Country(name: "Sweden", alpha2Code: "se"),
            Country(name: "Switzerland", alpha2Code: "ch"),
            Country(name: "Syrian Arab Republic", alpha2Code: "sy"),
            Country(name: "Tajikistan", alpha2Code: "tj"),
            Country(name: "Thailand", alpha2Code: "th"),
            Country(name: "Timor-Leste", alpha2Code: "tl"),
            Country(name: "Togo", alpha2Code: "tg"),
            Country(name: "Tonga", alpha2Code: "to"),
            Country(name: "Trinidad and Tobago", alpha2Code: "tt"),
            Country(name: "Tunisia", alpha2Code: "tn"),
            Country(name: "Turkey", alpha2Code: "tr"),
            Country(name: "Turkmenistan", alpha2Code: "tm"),
            Country(name: "Tuvalu", alpha2Code: "tv"),
            Country(name: "Uganda", alpha2Code: "ug"),
            Country(name: "Ukraine", alpha2Code: "ua"),
            Country(name: "United Arab Emirates", alpha2Code: "ae"),
            Country(name: "United Kingdom of Great Britain and Northern Ireland", alpha2Code: "gb"),
            Country(name: "United Republic of Tanzania", alpha2Code: "tz"),
            Country(name: "United States of America", alpha2Code: "us"),
            Country(name: "Uruguay", alpha2Code: "uy"),
            Country(name: "Uzbekistan", alpha2Code: "uz"),
            Country(name: "Vanuatu", alpha2Code: "vu"),
            Country(name: "Venezuela (Bolivarian Republic of)", alpha2Code: "ve"),
            Country(name: "Viet Nam", alpha2Code: "vn"),
            Country(name: "Yemen", alpha2Code: "ye"),
            Country(name: "Zambia", alpha2Code: "zm"),
            Country(name: "Zimbabwe", alpha2Code: "zw")
        ]
        
    }
}

