//
//  Currency.swift
//  Whooliday
//
//  Created by Tommaso Diegoli on 25/06/24.
//
class Currency: Identifiable, Codable, Hashable {
    let name: String
    let code: String
    
    init(name: String, code: String) {
        self.name = name
        self.code = code
    }
    
    // Implementing Hashable
    func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(code)
    }
    
    static func == (lhs: Currency, rhs: Currency) -> Bool {
        return lhs.name == rhs.name && lhs.code == rhs.code
    }
}

extension Currency {
    static var allCurrencies: [Currency] {
        [
            Currency(name: "Afghan Afghani", code: "AFN"),
            Currency(name: "Albanian Lek", code: "ALL"),
            Currency(name: "Algerian Dinar", code: "DZD"),
            Currency(name: "Argentine Peso", code: "ARS"),
            Currency(name: "Armenian Dram", code: "AMD"),
            Currency(name: "Australian Dollar", code: "AUD"),
            Currency(name: "Azerbaijani Manat", code: "AZN"),
            Currency(name: "Bahamian Dollar", code: "BSD"),
            Currency(name: "Bahraini Dinar", code: "BHD"),
            Currency(name: "Bangladeshi Taka", code: "BDT"),
            Currency(name: "Barbadian Dollar", code: "BBD"),
            Currency(name: "Belarusian Ruble", code: "BYN"),
            Currency(name: "Belize Dollar", code: "BZD"),
            Currency(name: "Bermudian Dollar", code: "BMD"),
            Currency(name: "Bhutanese Ngultrum", code: "BTN"),
            Currency(name: "Bolivian Boliviano", code: "BOB"),
            Currency(name: "Bosnia and Herzegovina Convertible Mark", code: "BAM"),
            Currency(name: "Botswana Pula", code: "BWP"),
            Currency(name: "Brazilian Real", code: "BRL"),
            Currency(name: "Brunei Dollar", code: "BND"),
            Currency(name: "Bulgarian Lev", code: "BGN"),
            Currency(name: "Burundi Franc", code: "BIF"),
            Currency(name: "Cambodian Riel", code: "KHR"),
            Currency(name: "Canadian Dollar", code: "CAD"),
            Currency(name: "Cape Verdean Escudo", code: "CVE"),
            Currency(name: "Cayman Islands Dollar", code: "KYD"),
            Currency(name: "Central African CFA Franc", code: "XAF"),
            Currency(name: "Chilean Peso", code: "CLP"),
            Currency(name: "Chinese Yuan", code: "CNY"),
            Currency(name: "Colombian Peso", code: "COP"),
            Currency(name: "Comorian Franc", code: "KMF"),
            Currency(name: "Congolese Franc", code: "CDF"),
            Currency(name: "Costa Rican Colón", code: "CRC"),
            Currency(name: "Croatian Kuna", code: "HRK"),
            Currency(name: "Cuban Peso", code: "CUP"),
            Currency(name: "Czech Koruna", code: "CZK"),
            Currency(name: "Danish Krone", code: "DKK"),
            Currency(name: "Djiboutian Franc", code: "DJF"),
            Currency(name: "Dominican Peso", code: "DOP"),
            Currency(name: "East Caribbean Dollar", code: "XCD"),
            Currency(name: "Egyptian Pound", code: "EGP"),
            Currency(name: "Eritrean Nakfa", code: "ERN"),
            Currency(name: "Ethiopian Birr", code: "ETB"),
            Currency(name: "Euro", code: "EUR"),
            Currency(name: "Falkland Islands Pound", code: "FKP"),
            Currency(name: "Fijian Dollar", code: "FJD"),
            Currency(name: "Gambian Dalasi", code: "GMD"),
            Currency(name: "Georgian Lari", code: "GEL"),
            Currency(name: "Ghanaian Cedi", code: "GHS"),
            Currency(name: "Gibraltar Pound", code: "GIP"),
            Currency(name: "Guatemalan Quetzal", code: "GTQ"),
            Currency(name: "Guinean Franc", code: "GNF"),
            Currency(name: "Guyanese Dollar", code: "GYD"),
            Currency(name: "Haitian Gourde", code: "HTG"),
            Currency(name: "Honduran Lempira", code: "HNL"),
            Currency(name: "Hong Kong Dollar", code: "HKD"),
            Currency(name: "Hungarian Forint", code: "HUF"),
            Currency(name: "Icelandic Króna", code: "ISK"),
            Currency(name: "Indian Rupee", code: "INR"),
            Currency(name: "Indonesian Rupiah", code: "IDR"),
            Currency(name: "Iranian Rial", code: "IRR"),
            Currency(name: "Iraqi Dinar", code: "IQD"),
            Currency(name: "Israeli New Shekel", code: "ILS"),
            Currency(name: "Jamaican Dollar", code: "JMD"),
            Currency(name: "Japanese Yen", code: "JPY"),
            Currency(name: "Jordanian Dinar", code: "JOD"),
            Currency(name: "Kazakhstani Tenge", code: "KZT"),
            Currency(name: "Kenyan Shilling", code: "KES"),
            Currency(name: "Kuwaiti Dinar", code: "KWD"),
            Currency(name: "Kyrgyzstani Som", code: "KGS"),
            Currency(name: "Lao Kip", code: "LAK"),
            Currency(name: "Lebanese Pound", code: "LBP"),
            Currency(name: "Lesotho Loti", code: "LSL"),
            Currency(name: "Liberian Dollar", code: "LRD"),
            Currency(name: "Libyan Dinar", code: "LYD"),
            Currency(name: "Macanese Pataca", code: "MOP"),
            Currency(name: "Malagasy Ariary", code: "MGA"),
            Currency(name: "Malawian Kwacha", code: "MWK"),
            Currency(name: "Malaysian Ringgit", code: "MYR"),
            Currency(name: "Maldivian Rufiyaa", code: "MVR"),
            Currency(name: "Mauritanian Ouguiya", code: "MRU"),
            Currency(name: "Mauritian Rupee", code: "MUR"),
            Currency(name: "Mexican Peso", code: "MXN"),
            Currency(name: "Moldovan Leu", code: "MDL"),
            Currency(name: "Mongolian Tugrik", code: "MNT"),
            Currency(name: "Moroccan Dirham", code: "MAD"),
            Currency(name: "Mozambican Metical", code: "MZN"),
            Currency(name: "Myanmar Kyat", code: "MMK"),
            Currency(name: "Namibian Dollar", code: "NAD"),
            Currency(name: "Nepalese Rupee", code: "NPR"),
            Currency(name: "New Taiwan Dollar", code: "TWD"),
            Currency(name: "New Zealand Dollar", code: "NZD"),
            Currency(name: "Nicaraguan Córdoba", code: "NIO"),
            Currency(name: "Nigerian Naira", code: "NGN"),
            Currency(name: "North Korean Won", code: "KPW"),
            Currency(name: "Norwegian Krone", code: "NOK"),
            Currency(name: "Omani Rial", code: "OMR"),
            Currency(name: "Pakistani Rupee", code: "PKR"),
            Currency(name: "Panamanian Balboa", code: "PAB"),
            Currency(name: "Papua New Guinean Kina", code: "PGK"),
            Currency(name: "Paraguayan Guarani", code: "PYG"),
            Currency(name: "Peruvian Sol", code: "PEN"),
            Currency(name: "Philippine Peso", code: "PHP"),
            Currency(name: "Polish Zloty", code: "PLN"),
            Currency(name: "Qatari Riyal", code: "QAR"),
            Currency(name: "Romanian Leu", code: "RON"),
            Currency(name: "Russian Ruble", code: "RUB"),
            Currency(name: "Rwandan Franc", code: "RWF"),
            Currency(name: "Saint Helena Pound", code: "SHP"),
            Currency(name: "Samoan Tala", code: "WST"),
            Currency(name: "Sao Tome and Principe Dobra", code: "STN"),
            Currency(name: "Saudi Riyal", code: "SAR"),
            Currency(name: "Serbian Dinar", code: "RSD"),
            Currency(name: "Seychellois Rupee", code: "SCR"),
            Currency(name: "Sierra Leonean Leone", code: "SLL"),
            Currency(name: "Singapore Dollar", code: "SGD"),
            Currency(name: "Solomon Islands Dollar", code: "SBD"),
            Currency(name: "Somali Shilling", code: "SOS"),
            Currency(name: "South African Rand", code: "ZAR"),
            Currency(name: "South Korean Won", code: "KRW"),
            Currency(name: "South Sudanese Pound", code: "SSP"),
            Currency(name: "Sri Lankan Rupee", code: "LKR"),
            Currency(name: "Sudanese Pound", code: "SDG"),
            Currency(name: "Surinamese Dollar", code: "SRD"),
            Currency(name: "Swazi Lilangeni", code: "SZL"),
            Currency(name: "Swedish Krona", code: "SEK"),
            Currency(name: "Swiss Franc", code: "CHF"),
            Currency(name: "Syrian Pound", code: "SYP"),
            Currency(name: "Tajikistani Somoni", code: "TJS"),
            Currency(name: "Tanzanian Shilling", code: "TZS"),
            Currency(name: "Thai Baht", code: "THB"),
            Currency(name: "Tongan Pa'anga", code: "TOP"),
            Currency(name: "Trinidad and Tobago Dollar", code: "TTD"),
            Currency(name: "Tunisian Dinar", code: "TND"),
            Currency(name: "Turkish Lira", code: "TRY"),
            Currency(name: "Turkmenistan Manat", code: "TMT"),
            Currency(name: "Ugandan Shilling", code: "UGX"),
            Currency(name: "Ukrainian Hryvnia", code: "UAH"),
            Currency(name: "United Arab Emirates Dirham", code: "AED"),
            Currency(name: "United States Dollar", code: "USD"),
            Currency(name: "Uruguayan Peso", code: "UYU"),
            Currency(name: "Uzbekistan Som", code: "UZS"),
            Currency(name: "Vanuatu Vatu", code: "VUV"),
            Currency(name: "Venezuelan Bolívar", code: "VES"),
            Currency(name: "Vietnamese Dong", code: "VND"),
            Currency(name: "Yemeni Rial", code: "YER"),
            Currency(name: "Zambian Kwacha", code: "ZMW"),
            Currency(name: "Zimbabwean Dollar", code: "ZWL")
        ]
    }
}
